import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import Header from '@/shared/ui/header';
import Footer from '@/shared/ui/footer';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} antialiased bg-background`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
